# Generated by Django 3.2.3 on 2021-06-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_coba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coba',
        ),
    ]
